[project]
name = "pylox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Philip Gillespie", email = "philip.gillespie91@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
pylox = "pylox:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
